#
#  1. Check we can parse gt3x v2 file without error
#  2. Test if the extracted epoch files have changed
#
name: gt3x

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  parsing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Compile Parser
        run: javac -cp java/JTransforms-3.1-with-dependencies.jar java/*.java

      - name: Prase gt3x V2 file
        run: |
          cd java
          java AccelerometerParser Tests/Resources/sampleV2.gt3x npyOutput:True  rawOutput:True

      - name: Check if the output file has changed
        run: |
          chmod +x java/Tests/Resources/compareOutput.sh
          ./java/Tests/Resources/compareOutput.sh
