#  1. Test parsing gt3x v2
#  2. Check output epoch files haven't changed

name: gt3x

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  gt3x:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/accelerometer/java/

    steps:
      - uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Compile java files
        run: javac -cp JTransforms-3.1-with-dependencies.jar *.java

      - name: Parse gt3x V2 file
        run: java AccelerometerParser Tests/Resources/gt3xV1.gt3x npyOutput:True  rawOutput:True timeZone:Brazil/West
