# Test installation for different OS (Ubuntu, Mac) and Python versions (3.7, 3.8)

name: install

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  install:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

        exclude:  # python <= 3.7 no longer supported in latest operating systems
          - python-version: "3.7"
        include:
          # use older macos for python 3.7
          - python-version: "3.7"
            os: macos-13
          # use older ubuntu for python 3.7
          - python-version: "3.7"
            os: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Compile java files
        run: javac -cp src/accelerometer/java/JTransforms-3.1-with-dependencies.jar src/accelerometer/java/*.java

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip install
        run: |
          pip install --upgrade pip
          pip install .

      - name: Import package and print version
        run: python -c "import accelerometer; print(accelerometer.__version__)"
