# Test installation for different OS (Ubuntu, Mac) and Python versions (3.7, 3.8)

name: install

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  install:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8]  # pandas dropped support for 3.6!

    steps:
      - uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Compile java files
        run: javac -cp src/accelerometer/java/JTransforms-3.1-with-dependencies.jar src/accelerometer/java/*.java

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip install
        run: |
          pip install --upgrade pip
          pip install .

      - name: Import package and print version
        run: python -c "import accelerometer; print(accelerometer.__version__)"
