name: regression test for processing sample data to epoch file

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  summary-check:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest numpy scipy pandas sklearn argparse datetime atexit warnings
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   # - name: Lint with flake8
   #   run: |
   #     # stop the build if there are Python syntax errors or undefined names
   #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
   #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
   #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Compile Parser
      run: javac -cp java/JTransforms-3.1-with-dependencies.jar java/*.java
    - name: Load data
      run: bash utilities/downloadDataModels.sh
    - name: Process data using accProcess.py
      run: python accProcess.py --deleteIntermediateFiles False data/sample.cwa
    - name: Compare epoch output
      uses: tianhaoz95/mirror-action@v1.0.1
      with:
         original: referenceFiles/epoch.csv.gz
         mirror: data/sample-epoch.csv.gz



